name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: chmod u+x configure ; sudo ./configure
    - name: make
      run: make
    - run: ./acc -T Tests/in/test1.c && chmod u+x a.out && ./a.out
    - name: make test
      run: make test
    - name: test
      run: ./test
