name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - run: ls
    - name: configure
      run: sudo ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    - name: test
      run: ./test
