name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: chmod u+x configure ; sudo ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    - name: test
      working-directory: ./
      run: ./test
    - run: ls Tests/out
