name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: chmod u+x configure ; sudo ./configure
    - run: ls /usr/bin | grep llvm
    - run: which llvm-link-18
    - name: make
      run: make
    - name: make test
      run: make test
    - name: test
      run: ./test
